name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  action-environment-debug:
    runs-on: ubuntu-latest
    steps:
    #  - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - run: npm install -g bats
      - name: Test run
        run: | 
          date
          ls -la
          pwd 
          echo "CIAO---------------------------------"
          env
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"